export const ACTION_TYPES = {
    SLOT_API_PENDING: "SLOT_API_PENDING",
    SLOT_API_NOT_AVAILABLE: "SLOT_API_NOT_AVAILABLE",
    SLOT_API_COMPLETE: "SLOT_API_COMPLETE",
    SLOT_API_ERROR: "SLOT_API_ERROR",
    SET_DOCTOR_INFO: "SET_DOCTOR_INFO",
    SET_DATES: "SET_DATES",
    SET_TRANSLATE: "SET_TRANSLATE",
    SET_SLOTS_DATA: "SET_SLOTS_DATA",
    SET_SHOW_TIME_SLOT: "SET_SHOW_TIME_SLOT",
    SET_SERVICES: "SET_SERVICES",
    SET_HOSPITAL_LIST: "SET_HOSPITAL_LIST",
    SET_SLOTS_LOADING: "SET_SLOTS_LOADING",
    SET_DOCTOR_NOT_AVAILABLE: "SET_DOCTOR_NOT_AVAILABLE",
    ERROR: "ERROR",
    SET_APPOINTMENT_ALREADY_EXIST_DIALOG:
        "SET_APPOINTMENT_ALREADY_EXIST_DIALOG",
    SET_APPOINTMENT_BOOKED_DIALOG: "SET_APPOINTMENT_BOOKED_DIALOG",
};
